### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hadifarnoud**
typo

### CODE REVIEW

**Comment by BlaineMoore** [comment]
Thanks, but this is not a typo. Amazon SNS is referencing Amazon Simple Notification Service, not Amazon Simple Email Service.

**Comment by stevebaldry** [comment]
Hi Blainemoore.

I am using Sendy without any SMTP - directly on a server.  I wondered how I could setup Sendy to just send any bounces or complaints directly to an email address so they can be manually tracked ?Even better would be to use the webhooks to have them shown in Sendy.  I'm not a coder so not sure how to set this up. 

Thanks
Steve

**Comment by BlaineMoore** [comment]
Hi Steve,

Processing bounce and spam complaints would be something handled by your
SMTP server software. You would have to look into what is installed on your
server, and whether it can call an external webhook with those
notifications, and if so, then you would need to setup a bounce and
complaint handling end point for it.  The files in my project could
certainly be used as a good template for quickly and easily handling a
webhook end point, but you will have to see about how to turn on
notifications in your server software (if that's possible in whatever you
are using.)

I never send mail locally and always use a third party, be that SES,
Critsend or (in the past) Mandrill.

**Comment by stevebaldry** [comment]
Hi,
Thanks for your quick reply.
I'm not using SMTP - I am sending directly from the server. I've been using this successfully with my hosting company who support it fully using software other than Sendy.
My requirement is actually simpler than I originally thought after doing some investigation.
All I want to do is change the email address that Sendy uses for Bounces.  I believe this is defined with the SPF before the message is sent.   I don't need to process the bounces as I can do this from the emails received manually.  Complaints are setup through FBLs anyway.
I cannot see an option in Sendy for changing the bounce address, so thought it may be inside the code somewhere ?
Thank you for your reply anyway, and I may well find some good use for your webooks at a later stage.

Steve

Date: Tue, 24 Nov 2015 11:20:36 -0800

**Comment by BlaineMoore** [comment]
Glad that I could help. (Even if only a little bit.)

And by SMTP server I meant the software itself that does it, even if hosted
on your own machine. The SMTP relay services are basically just large, well
optimized SMTP servers with APIs for sending messages faster than you could
by doing it one at a time.

Good luck!

**Pull request closed without merging**
